### ISSUE TITLE
Add automation for TG cases

### ISSUE THREAD

**Issue by sudevschiz** [bee-rickey/webScraper#23]
@bee-rickey  TG bulletin has the new confirmed cases in a table. Although it's just a 1 minute job to fill the numbers manually, would be nice if we can automate that too.

This table: https://twitter.com/Eatala_Rajender/status/1315508706646261762/photo/3

Brownie points if you extract the recovered and deceased values too ;)

**Comment by bee-rickey** [comment]
Fixed with latest update.
